# This file will be generated by CDK at synth time with actual configuration values
AZURE_TENANT_ID = 'TENANT_ID_PLACEHOLDER'
# amazonq-ignore-next-line
AZURE_CLIENT_ID = 'CLIENT_ID_PLACEHOLDER'
REDIRECT_URI = 'REDIRECT_URI_PLACEHOLDER'
HMAC_SECRET_ARN = 'SECRET_ARN_PLACEHOLDER'
